[build]
# construir a aplicação
builder = "NIXPACKS"

[deploy]
# comando inicial para deploy
startCommand = "java -jar target/review-analyzer-1.0-SNAPSHOT.jar"

# definir o tipo de aplicação
[nickspacks]
providers = ["java"]